services:
  postgres:
    container_name: renova_db
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./db-data:/data
